FROM localhost/fpsloppa-server-toolchain:godot-4.7.2-jammy
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    mingw-w64 libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev \
    libwayland-dev libxkbcommon-dev libasound2-dev libpulse-dev libudev-dev \
    libdbus-1-dev libfontconfig1-dev libspeechd-dev libvulkan-dev \
    && rm -rf /var/lib/apt/lists/*
RUN update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix \
    && update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
