extends RefCounted
# Generated by tools/build_mode_audio.py.
const SOUNDS={
 "cs16_weapon_0": [
  "res://deathmatch/audio/modes/cs16_weapon_0_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_0_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_0_v2.wav"
 ],
 "cs16_weapon_1": [
  "res://deathmatch/audio/modes/cs16_weapon_1_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_1_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_1_v2.wav"
 ],
 "cs16_weapon_2": [
  "res://deathmatch/audio/modes/cs16_weapon_2_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_2_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_2_v2.wav"
 ],
 "cs16_weapon_3": [
  "res://deathmatch/audio/modes/cs16_weapon_3_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_3_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_3_v2.wav"
 ],
 "cs16_weapon_4": [
  "res://deathmatch/audio/modes/cs16_weapon_4_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_4_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_4_v2.wav"
 ],
 "cs16_weapon_5": [
  "res://deathmatch/audio/modes/cs16_weapon_5_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_5_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_5_v2.wav"
 ],
 "cs16_weapon_6": [
  "res://deathmatch/audio/modes/cs16_weapon_6_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_6_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_6_v2.wav"
 ],
 "cs16_weapon_7": [
  "res://deathmatch/audio/modes/cs16_weapon_7_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_7_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_7_v2.wav"
 ],
 "cs16_weapon_8": [
  "res://deathmatch/audio/modes/cs16_weapon_8_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_8_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_8_v2.wav"
 ],
 "cs16_weapon_9": [
  "res://deathmatch/audio/modes/cs16_weapon_9_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_9_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_9_v2.wav"
 ],
 "cs16_weapon_10": [
  "res://deathmatch/audio/modes/cs16_weapon_10_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_10_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_10_v2.wav"
 ],
 "cs16_weapon_11": [
  "res://deathmatch/audio/modes/cs16_weapon_11_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_11_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_11_v2.wav"
 ],
 "quake_weapon_0": [
  "res://deathmatch/audio/modes/quake_weapon_0_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_0_v1.wav"
 ],
 "quake_weapon_1": [
  "res://deathmatch/audio/modes/quake_weapon_1_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_1_v1.wav"
 ],
 "quake_weapon_2": [
  "res://deathmatch/audio/modes/quake_weapon_2_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_2_v1.wav"
 ],
 "quake_weapon_3": [
  "res://deathmatch/audio/modes/quake_weapon_3_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_3_v1.wav"
 ],
 "quake_weapon_4": [
  "res://deathmatch/audio/modes/quake_weapon_4_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_4_v1.wav"
 ],
 "quake_weapon_5": [
  "res://deathmatch/audio/modes/quake_weapon_5_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_5_v1.wav"
 ],
 "quake_weapon_6": [
  "res://deathmatch/audio/modes/quake_weapon_6_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_6_v1.wav"
 ],
 "quake_weapon_7": [
  "res://deathmatch/audio/modes/quake_weapon_7_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_7_v1.wav"
 ],
 "quake_weapon_8": [
  "res://deathmatch/audio/modes/quake_weapon_8_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_8_v1.wav"
 ],
 "quake_weapon_9": [
  "res://deathmatch/audio/modes/quake_weapon_9_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_9_v1.wav"
 ],
 "ut99_weapon_0": [
  "res://deathmatch/audio/modes/ut99_weapon_0_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_0_v1.wav"
 ],
 "ut99_weapon_1": [
  "res://deathmatch/audio/modes/ut99_weapon_1_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_1_v1.wav"
 ],
 "ut99_weapon_2": [
  "res://deathmatch/audio/modes/ut99_weapon_2_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_2_v1.wav"
 ],
 "ut99_weapon_3": [
  "res://deathmatch/audio/modes/ut99_weapon_3_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_3_v1.wav"
 ],
 "ut99_weapon_4": [
  "res://deathmatch/audio/modes/ut99_weapon_4_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_4_v1.wav"
 ],
 "ut99_weapon_5": [
  "res://deathmatch/audio/modes/ut99_weapon_5_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_5_v1.wav"
 ],
 "ut99_weapon_6": [
  "res://deathmatch/audio/modes/ut99_weapon_6_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_6_v1.wav"
 ],
 "ut99_weapon_7": [
  "res://deathmatch/audio/modes/ut99_weapon_7_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_7_v1.wav"
 ],
 "ut99_weapon_8": [
  "res://deathmatch/audio/modes/ut99_weapon_8_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_8_v1.wav"
 ],
 "ut99_weapon_9": [
  "res://deathmatch/audio/modes/ut99_weapon_9_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_9_v1.wav"
 ],
 "ut99_weapon_10": [
  "res://deathmatch/audio/modes/ut99_weapon_10_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_10_v1.wav"
 ],
 "ut99_weapon_11": [
  "res://deathmatch/audio/modes/ut99_weapon_11_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_11_v1.wav"
 ],
 "tribes_weapon_0": [
  "res://deathmatch/audio/modes/tribes_weapon_0_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_0_v1.wav"
 ],
 "tribes_weapon_1": [
  "res://deathmatch/audio/modes/tribes_weapon_1_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_1_v1.wav"
 ],
 "tribes_weapon_2": [
  "res://deathmatch/audio/modes/tribes_weapon_2_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_2_v1.wav"
 ],
 "tribes_weapon_3": [
  "res://deathmatch/audio/modes/tribes_weapon_3_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_3_v1.wav"
 ],
 "tribes_weapon_4": [
  "res://deathmatch/audio/modes/tribes_weapon_4_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_4_v1.wav"
 ],
 "tribes_weapon_5": [
  "res://deathmatch/audio/modes/tribes_weapon_5_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_5_v1.wav"
 ],
 "tribes_weapon_6": [
  "res://deathmatch/audio/modes/tribes_weapon_6_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_6_v1.wav"
 ],
 "tribes_weapon_7": [
  "res://deathmatch/audio/modes/tribes_weapon_7_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_7_v1.wav"
 ],
 "tribes_weapon_8": [
  "res://deathmatch/audio/modes/tribes_weapon_8_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_8_v1.wav"
 ],
 "tribes_weapon_9": [
  "res://deathmatch/audio/modes/tribes_weapon_9_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_9_v1.wav"
 ],
 "tribes_weapon_10": [
  "res://deathmatch/audio/modes/tribes_weapon_10_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_10_v1.wav"
 ],
 "tribes_weapon_11": [
  "res://deathmatch/audio/modes/tribes_weapon_11_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_11_v1.wav"
 ],
 "ut99_weapon_0_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_0_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_0_alt_v1.wav"
 ],
 "ut99_weapon_1_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_1_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_1_alt_v1.wav"
 ],
 "ut99_weapon_2_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_2_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_2_alt_v1.wav"
 ],
 "ut99_weapon_3_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_3_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_3_alt_v1.wav"
 ],
 "ut99_weapon_4_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_4_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_4_alt_v1.wav"
 ],
 "ut99_weapon_5_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_5_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_5_alt_v1.wav"
 ],
 "ut99_weapon_6_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_6_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_6_alt_v1.wav"
 ],
 "ut99_weapon_7_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_7_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_7_alt_v1.wav"
 ],
 "ut99_weapon_8_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_8_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_8_alt_v1.wav"
 ],
 "ut99_weapon_9_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_9_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_9_alt_v1.wav"
 ],
 "ut99_weapon_10_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_10_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_10_alt_v1.wav"
 ],
 "ut99_weapon_11_alt": [
  "res://deathmatch/audio/modes/ut99_weapon_11_alt_v0.wav",
  "res://deathmatch/audio/modes/ut99_weapon_11_alt_v1.wav"
 ],
 "cs16_weapon_2_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_2_alt_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_2_alt_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_2_alt_v2.wav"
 ],
 "cs16_weapon_7_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_7_alt_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_7_alt_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_7_alt_v2.wav"
 ],
 "quake_explosion": [
  "res://deathmatch/audio/modes/quake_explosion_v0.wav",
  "res://deathmatch/audio/modes/quake_explosion_v1.wav"
 ],
 "quake_bounce": [
  "res://deathmatch/audio/modes/quake_bounce_v0.wav",
  "res://deathmatch/audio/modes/quake_bounce_v1.wav"
 ],
 "ut99_explosion": [
  "res://deathmatch/audio/modes/ut99_explosion_v0.wav",
  "res://deathmatch/audio/modes/ut99_explosion_v1.wav"
 ],
 "ut99_bounce": [
  "res://deathmatch/audio/modes/ut99_bounce_v0.wav",
  "res://deathmatch/audio/modes/ut99_bounce_v1.wav"
 ],
 "tribes_explosion": [
  "res://deathmatch/audio/modes/tribes_explosion_v0.wav",
  "res://deathmatch/audio/modes/tribes_explosion_v1.wav"
 ],
 "tribes_bounce": [
  "res://deathmatch/audio/modes/tribes_bounce_v0.wav",
  "res://deathmatch/audio/modes/tribes_bounce_v1.wav"
 ],
 "ut99_combo": [
  "res://deathmatch/audio/modes/ut99_combo_v0.wav",
  "res://deathmatch/audio/modes/ut99_combo_v1.wav"
 ],
 "cs16_weapon_0_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_0_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_0_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_0_v2.wav"
 ],
 "cs16_weapon_1_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_1_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_1_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_1_v2.wav"
 ],
 "cs16_weapon_3_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_3_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_3_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_3_v2.wav"
 ],
 "cs16_weapon_4_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_4_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_4_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_4_v2.wav"
 ],
 "cs16_weapon_5_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_5_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_5_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_5_v2.wav"
 ],
 "cs16_weapon_6_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_6_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_6_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_6_v2.wav"
 ],
 "cs16_weapon_8_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_8_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_8_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_8_v2.wav"
 ],
 "cs16_weapon_9_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_9_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_9_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_9_v2.wav"
 ],
 "cs16_weapon_10_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_10_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_10_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_10_v2.wav"
 ],
 "cs16_weapon_11_alt": [
  "res://deathmatch/audio/modes/cs16_weapon_11_v0.wav",
  "res://deathmatch/audio/modes/cs16_weapon_11_v1.wav",
  "res://deathmatch/audio/modes/cs16_weapon_11_v2.wav"
 ],
 "quake_weapon_0_alt": [
  "res://deathmatch/audio/modes/quake_weapon_0_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_0_v1.wav"
 ],
 "quake_weapon_1_alt": [
  "res://deathmatch/audio/modes/quake_weapon_1_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_1_v1.wav"
 ],
 "quake_weapon_2_alt": [
  "res://deathmatch/audio/modes/quake_weapon_2_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_2_v1.wav"
 ],
 "quake_weapon_3_alt": [
  "res://deathmatch/audio/modes/quake_weapon_3_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_3_v1.wav"
 ],
 "quake_weapon_4_alt": [
  "res://deathmatch/audio/modes/quake_weapon_4_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_4_v1.wav"
 ],
 "quake_weapon_5_alt": [
  "res://deathmatch/audio/modes/quake_weapon_5_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_5_v1.wav"
 ],
 "quake_weapon_6_alt": [
  "res://deathmatch/audio/modes/quake_weapon_6_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_6_v1.wav"
 ],
 "quake_weapon_7_alt": [
  "res://deathmatch/audio/modes/quake_weapon_7_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_7_v1.wav"
 ],
 "quake_weapon_8_alt": [
  "res://deathmatch/audio/modes/quake_weapon_8_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_8_v1.wav"
 ],
 "quake_weapon_9_alt": [
  "res://deathmatch/audio/modes/quake_weapon_9_v0.wav",
  "res://deathmatch/audio/modes/quake_weapon_9_v1.wav"
 ],
 "tribes_weapon_0_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_0_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_0_v1.wav"
 ],
 "tribes_weapon_1_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_1_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_1_v1.wav"
 ],
 "tribes_weapon_2_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_2_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_2_v1.wav"
 ],
 "tribes_weapon_3_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_3_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_3_v1.wav"
 ],
 "tribes_weapon_4_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_4_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_4_v1.wav"
 ],
 "tribes_weapon_5_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_5_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_5_v1.wav"
 ],
 "tribes_weapon_6_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_6_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_6_v1.wav"
 ],
 "tribes_weapon_7_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_7_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_7_v1.wav"
 ],
 "tribes_weapon_8_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_8_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_8_v1.wav"
 ],
 "tribes_weapon_9_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_9_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_9_v1.wav"
 ],
 "tribes_weapon_10_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_10_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_10_v1.wav"
 ],
 "tribes_weapon_11_alt": [
  "res://deathmatch/audio/modes/tribes_weapon_11_v0.wav",
  "res://deathmatch/audio/modes/tribes_weapon_11_v1.wav"
 ]
}
