extends RefCounted
# Generated by tools/balance_weapon_audio.py; do not amplify quiet recordings.
const TRIM_DB = {
	"impactPunch_heavy_000.ogg":-8.04,
	"impactPunch_heavy_001.ogg":-7.83,
	"impactPunch_heavy_002.ogg":-8.04,
	"impactPunch_heavy_003.ogg":-8.12,
	"impactPunch_heavy_004.ogg":-8.04,
	"weapon_1.wav":-13.13,
	"weapon_2_0.wav":-0.37,
	"weapon_2_1.wav":-3.16,
	"weapon_2_2.wav":-0.62,
	"weapon_2_3.wav":-3.04,
	"weapon_3_0.wav":-0.51,
	"weapon_4_0.wav":-0.53,
	"weapon_5_0.wav":-4.82,
	"weapon_5_1.wav":-4.65,
	"weapon_5_2.wav":-8.46,
	"weapon_5_3.wav":-4.97,
	"weapon_6.wav":-8.03,
	"weapon_7.wav":-13.82,
	"weapon_8.wav":-4.95,
}
