extends RefCounted
# Generated by tools/balance_weapon_audio.py; do not amplify quiet recordings.
const TRIM_DB = {
	"impactPunch_heavy_000.ogg":-8.04,
	"impactPunch_heavy_001.ogg":-7.83,
	"impactPunch_heavy_002.ogg":-8.04,
	"impactPunch_heavy_003.ogg":-8.12,
	"impactPunch_heavy_004.ogg":-8.04,
	"weapon_1.wav":-8.65,
	"weapon_2.wav":-6.16,
	"weapon_3.wav":-2.38,
	"weapon_4.wav":-4.83,
	"weapon_5.wav":-11.17,
	"weapon_6.wav":-4.48,
	"weapon_7.wav":-8.1,
	"weapon_8.wav":-3.54,
	"weapon_9.wav":-2.8,
}
