FROM docker.io/library/ubuntu@sha256:281c5745f657873d78e5531fc5ba8575f46ab7769b94550ac99543f122679986
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential python3 python3-pip pkg-config ca-certificates && python3 -m pip install --no-cache-dir scons==4.9.1 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
ENTRYPOINT ["scons"]
