extends RefCounted
# Generated by tools/build_weapon_actions.py.
const SOUNDS = {
	"saw_idle": {
		"path": "res://deathmatch/audio/weapon-actions/saw_idle.res",
		"loop": true
	},
	"saw_ready": {
		"path": "res://deathmatch/audio/weapon-actions/saw_ready.res",
		"loop": false
	},
	"saw_settle": {
		"path": "res://deathmatch/audio/weapon-actions/saw_settle.res",
		"loop": false
	},
	"rotor_run": {
		"path": "res://deathmatch/audio/weapon-actions/rotor_run.res",
		"loop": true
	},
	"rotor_start": {
		"path": "res://deathmatch/audio/weapon-actions/rotor_start.res",
		"loop": false
	},
	"rotor_stop": {
		"path": "res://deathmatch/audio/weapon-actions/rotor_stop.res",
		"loop": false
	},
	"hammer_charge": {
		"path": "res://deathmatch/audio/weapon-actions/hammer_charge.res",
		"loop": true
	},
	"hammer_start": {
		"path": "res://deathmatch/audio/weapon-actions/hammer_start.res",
		"loop": false
	},
	"pressure_release": {
		"path": "res://deathmatch/audio/weapon-actions/pressure_release.res",
		"loop": false
	},
	"bio_charge": {
		"path": "res://deathmatch/audio/weapon-actions/bio_charge.res",
		"loop": true
	},
	"bio_valve": {
		"path": "res://deathmatch/audio/weapon-actions/bio_valve.res",
		"loop": false
	},
	"bio_settle": {
		"path": "res://deathmatch/audio/weapon-actions/bio_settle.res",
		"loop": false
	},
	"rocket_load": {
		"path": "res://deathmatch/audio/weapon-actions/rocket_load.res",
		"loop": false
	},
	"launcher_close": {
		"path": "res://deathmatch/audio/weapon-actions/launcher_close.res",
		"loop": false
	},
	"pulse_run": {
		"path": "res://deathmatch/audio/weapon-actions/pulse_run.res",
		"loop": true
	},
	"pulse_stop": {
		"path": "res://deathmatch/audio/weapon-actions/pulse_stop.res",
		"loop": false
	},
	"energy_select": {
		"path": "res://deathmatch/audio/weapon-actions/energy_select.res",
		"loop": false
	},
	"lightning_start": {
		"path": "res://deathmatch/audio/weapon-actions/lightning_start.res",
		"loop": false
	},
	"lightning_run": {
		"path": "res://deathmatch/audio/weapon-actions/lightning_run.res",
		"loop": true
	},
	"lightning_stop": {
		"path": "res://deathmatch/audio/weapon-actions/lightning_stop.res",
		"loop": false
	},
	"disc_reseat": {
		"path": "res://deathmatch/audio/weapon-actions/disc_reseat.res",
		"loop": false
	},
	"plasma_vent": {
		"path": "res://deathmatch/audio/weapon-actions/plasma_vent.res",
		"loop": false
	},
	"laser_reset": {
		"path": "res://deathmatch/audio/weapon-actions/laser_reset.res",
		"loop": false
	},
	"mortar_reseat": {
		"path": "res://deathmatch/audio/weapon-actions/mortar_reseat.res",
		"loop": false
	},
	"elf_run": {
		"path": "res://deathmatch/audio/weapon-actions/elf_run.res",
		"loop": true
	},
	"repair_run": {
		"path": "res://deathmatch/audio/weapon-actions/repair_run.res",
		"loop": true
	},
	"flame_ignite": {
		"path": "res://deathmatch/audio/weapon-actions/flame_ignite.res",
		"loop": false
	},
	"flame_out": {
		"path": "res://deathmatch/audio/weapon-actions/flame_out.res",
		"loop": false
	},
	"pistol_draw": {
		"path": "res://deathmatch/audio/weapon-actions/pistol_draw.res",
		"loop": false
	},
	"rifle_draw": {
		"path": "res://deathmatch/audio/weapon-actions/rifle_draw.res",
		"loop": false
	},
	"bolt_cycle": {
		"path": "res://deathmatch/audio/weapon-actions/bolt_cycle.res",
		"loop": false
	}
}
