"""Calibrate all live weapon routes without changing the recorded waveform.

Run with --check to detect stale gains. Requires Godot, ffmpeg and numpy.
Uses maximum 50-ms RMS, 4x oversampled peaks and energy per firing cycle.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import subprocess
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
LEVELS = ROOT / 'deathmatch/audio/weapon_levels.gd'
RATE = 48000
PEAK_CEILING = -3.0
SUSTAINED_CEILING = -17.0
BODY_TARGET = -17.0


def db(value):
    return 20 * math.log10(max(float(value), 1e-12))


def measure(path):
    pcm = subprocess.check_output(['ffmpeg', '-v', 'error', '-i', str(path), '-ac', '1', '-ar', str(RATE * 4), '-f', 'f32le', '-'])
    oversampled = np.frombuffer(pcm, dtype='<f4').astype(float)
    x = oversampled[::4]
    if not len(x) or not np.isfinite(x).all() or not np.any(x):
        raise ValueError(f'Empty, silent or invalid weapon clip: {path}')
    window = min(len(x), RATE // 20)
    integral = np.r_[0., np.cumsum(x*x)]
    rms = math.sqrt(float(np.max(integral[window:] - integral[:-window])) / window)
    return dict(body_dbfs=db(rms), true_peak_dbfs=db(np.max(np.abs(oversampled))), energy=float(np.sum(x*x)/RATE))


def target(kinds):
    if any(k.startswith('cs_reload_') or k == 'de_snip' for k in kinds):return -20.0
    if any(k.endswith('_bounce') for k in kinds):return -23.0
    if 'tribes_weapon_11' in kinds:return -24.0
    if 'tribes_weapon_8' in kinds:return -22.0
    if any(k in ['weapon_0','quake_weapon_0','quake_weapon_1','cs16_weapon_0','tribes_weapon_9','tribes_weapon_10'] for k in kinds):return -20.0
    return BODY_TARGET


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    parser.add_argument('--output',type=Path,default=ROOT/'test-results/weapon-levels')
    args=parser.parse_args();out=args.output.resolve();out.mkdir(parents=True,exist_ok=True)
    result=subprocess.run(['godot','--headless','--path',str(ROOT),'--xr-mode','off','--audio-driver','Dummy','--log-file',str(out/'inventory-engine.log'),'--script','res://tools/weapon_audio_inventory.gd','--',str(out)],capture_output=True,text=True)
    (out/'inventory.log').write_text(result.stdout+result.stderr)
    result.check_returncode()
    if 'SCRIPT ERROR' in result.stdout+result.stderr:raise RuntimeError('Inventory script failed')
    inventory=json.loads((out/'inventory.json').read_text());rows=[];trims={}
    old_text=LEVELS.read_text()
    old={name:float(value) for name,value in re.findall(r'"([^"]+)":\s*(-?[\d.]+)',old_text)}
    failures=[]
    for row in inventory:
        stats=measure(row['decoded']);sustained=db(math.sqrt(stats['energy']/row['cycle']))
        goal=target(row['kinds'])
        gain=math.floor(min(goal-stats['body_dbfs'],PEAK_CEILING-stats['true_peak_dbfs'],SUSTAINED_CEILING-sustained)*100)/100
        trims[row['path']]=gain
        previous=old.get(row['path'],old.get(Path(row['path']).name,0) if any(k.startswith('weapon_') for k in row['kinds']) else 0)
        final_body=stats['body_dbfs']+gain
        if final_body<goal-3.5:failures.append(row['path']+': body remains too quiet')
        if stats['true_peak_dbfs']+gain>PEAK_CEILING+.001 or sustained+gain>SUSTAINED_CEILING+.001:failures.append(row['path']+': level ceiling exceeded')
        row.update(stats,target_body_dbfs=goal,sustained_dbfs=sustained,gain_db=gain,
                   before_body_dbfs=stats['body_dbfs']+previous,after_body_dbfs=final_body,
                   after_true_peak_dbfs=stats['true_peak_dbfs']+gain,after_sustained_dbfs=sustained+gain,
                   gain_change_db=round(gain-previous,2),sha256=hashlib.sha256((ROOT/row['path'].removeprefix('res://')).read_bytes()).hexdigest())
        rows.append(row)
    output='extends RefCounted\n# Generated by tools/balance_weapon_audio.py; boosts and cuts, no waveform changes.\n'
    output+='const TRIM_DB = '+json.dumps(dict(sorted(trims.items())),indent='\t')+'\n'
    output+='''static func applies(kind: String) -> bool:
\treturn kind.begins_with("weapon_") or kind.contains("_weapon_") or kind=="flamethrower" or kind.begins_with("cs_reload_") or kind=="de_snip" or kind=="explosion" or kind.ends_with("_explosion") or kind.ends_with("_bounce") or kind=="ut99_combo"
static func gain_db(kind: String,path: String) -> float:
\treturn float(TRIM_DB.get(path,0.0)) if applies(kind) else 0.0
'''
    if args.check:
        if old_text!=output:failures.append('Generated gain table is stale')
    elif not failures:LEVELS.write_text(output)
    report=dict(streams=len(rows),failures=failures,method='maximum 50 ms RMS with 4x true-peak and cadence-energy limits',
                peak_ceiling_dbfs=PEAK_CEILING,sustained_ceiling_dbfs=SUSTAINED_CEILING,clips=rows)
    (out/'normalization.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps(dict(streams=len(rows),failures=failures,gain_change_db=[min(r['gain_change_db'] for r in rows),max(r['gain_change_db'] for r in rows)])))
    raise SystemExit(bool(failures))


if __name__=='__main__':main()
