"""Generate attenuation-only trims from the shipped clips (requires ffmpeg).

Cap peaks at -6 dBFS and energy per firing cycle at -20 dBFS. The latter
includes overlapping tails, so fast plasma/saw fire cannot dominate the mix.
Run again after replacing sounds or changing weapon cadence.
"""
from pathlib import Path
import array
import math
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
AUDIO = ROOT / "deathmatch/audio"
cycles = [float(v) for v in re.findall(r'"cycle":([\d.]+)', (ROOT / "deathmatch/weapons.gd").read_text())]
trims = {}
for weapon, cycle in enumerate(cycles):
    paths = [AUDIO / "doom-style" / f"weapon_{weapon}.wav"] if (AUDIO / "doom-style" / f"weapon_{weapon}.wav").exists() else sorted((AUDIO / "recorded").glob(f"weapon_{weapon}_*.wav"))
    if weapon == 0:
        paths = sorted((AUDIO / "recorded").glob("impactPunch_heavy_*.ogg"))
    if not paths:
        paths = [AUDIO / f"weapon_{weapon}.wav"]
    for path in paths:
        pcm = subprocess.check_output(["ffmpeg", "-v", "error", "-i", str(path), "-ac", "1", "-ar", "48000", "-f", "f32le", "-"])
        samples = array.array("f", pcm)
        if sys.byteorder != "little":
            samples.byteswap()
        peak_db = 20 * math.log10(max(max(map(abs, samples)), 1e-9))
        sustained_db = 10 * math.log10(max(sum(x*x for x in samples) / 48000 / cycle, 1e-18))
        trim = round(min(0.0, -6.0 - peak_db, -20.0 - sustained_db), 2)
        trims[path.name] = trim
        print(f"{path.name}: peak {peak_db:.1f}, sustained {sustained_db:.1f}, trim {trim:.2f} dB")
output = 'extends RefCounted\n# Generated by tools/balance_weapon_audio.py; do not amplify quiet recordings.\nconst TRIM_DB = {\n'
output += ''.join(f'\t"{name}":{trim},\n' for name, trim in sorted(trims.items()))
output += '}\n'
(AUDIO / "weapon_levels.gd").write_text(output)
