"""Deterministic experimental SFX derived from the existing licensed arena bank.
Run with Python 3 and ffmpeg. No commercial Quake/UT samples are used.
"""
from pathlib import Path
import argparse, array, hashlib, json, math, random, subprocess, wave
ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'deathmatch/audio/doom-style'
OUT=ROOT/'deathmatch/audio/experimental'
RATE=22050

def decode(path,pitch):
    raw=subprocess.check_output(['ffmpeg','-v','error','-i',str(path),'-ac','1','-ar',str(RATE),'-af',f'asetrate={int(RATE*pitch)},aresample={RATE},highpass=f=65,lowpass=f=8000','-f','f32le','-'])
    return list(array.array('f',raw))

def axe_swing(label):
    # Original CC0 air displacement: a broad noise swish, without motor tones.
    rng=random.Random('axe-swing-'+label)
    duration=.26 if label.endswith('_alt') else .30
    values=[];low=0.;bass=0.
    for i in range(int(RATE*duration)):
        t=i/RATE;u=t/duration;noise=rng.uniform(-1,1)
        cutoff=900+2200*math.sin(math.pi*u)**2
        low+=(noise-low)*(1-math.exp(-2*math.pi*cutoff/RATE))
        bass+=(low-bass)*(1-math.exp(-2*math.pi*160/RATE))
        values.append((low-bass)*math.sin(math.pi*u)**2)
    return values

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--axe-only',action='store_true',help='Regenerate only the four Quake axe clips and their manifest entries')
    args=parser.parse_args()
    OUT.mkdir(exist_ok=True); rows=[]
    for rules in ['quake','ut99']:
        for label in [f'weapon_{i}{alt}' for i in range(10 if rules=='quake' else 12) for alt in ['', '_alt']]+['explosion','bounce','combo']:
            is_axe=rules=='quake' and label in ['weapon_0','weapon_0_alt','weapon_1','weapon_1_alt']
            if args.axe_only and not is_axe:continue
            slot=int(label.split('_')[1]) if label.startswith('weapon_') else 6
            alias=([1,1,3,4,6,5,6,5,7,5] if rules=='quake' else [1,7,2,7,4,5,6,7,8,5,5,7])[slot] if label.startswith('weapon_') else 6
            source=BASE/(f'weapon_{alias}.wav' if label.startswith('weapon_') else 'explosion.wav')
            if label=="bounce":source=ROOT/"deathmatch/audio/recorded/impactMetal_light_000.ogg"
            pitch=(.83 if rules=='quake' else 1.12)*(1.14 if label.endswith('_alt') else 1)
            values=axe_swing(label) if is_axe else decode(source,pitch)
            duration=.13 if slot in [5,7,8] and rules=='quake' else .18 if slot in [5,7] else .46
            if not label.startswith('weapon_'):duration=.08 if label=='bounce' else .7
            n=min(len(values),int(RATE*duration));values=values[:n]
            rng=random.Random(rules+label)
            # Quake nails get a sharp metal contact; UT energy gets resonant tails.
            energy=rules=='ut99' and slot in [1,3,7,8,10,11] or rules=='quake' and slot==8
            for i in range(0 if is_axe else n):
                t=i/RATE;env=math.exp(-t*(18 if label=='bounce' else 10))
                detail=(math.sin(2*math.pi*(220+slot*61)*t+5*math.sin(2*math.pi*31*t))*.14 if energy else rng.uniform(-.10,.10)*math.exp(-t*130))
                values[i]=(values[i]+detail*env)*min(1,i/22)*min(1,(n-i)/220)
            mean=sum(values)/n;values=[v-mean for v in values]
            rms=math.sqrt(sum(v*v for v in values)/n);peak=max(map(abs,values))
            gain=min(10**(-17/20)/max(rms,1e-8),10**(-1/20)/max(peak,1e-8))
            values=[v*gain for v in values];path=OUT/f'{rules}_{label}.wav'
            with wave.open(str(path),'wb') as f:
                f.setnchannels(1);f.setsampwidth(2);f.setframerate(RATE);f.writeframes(array.array('h',(round(v*32767) for v in values)).tobytes())
            rows.append(dict(file=path.name,source="original procedural axe swing (CC0-1.0)" if is_axe else str(source.relative_to(ROOT)),source_sha256=None if is_axe else hashlib.sha256(source.read_bytes()).hexdigest(),sha256=hashlib.sha256(path.read_bytes()).hexdigest(),seconds=n/RATE,peak_dbfs=20*math.log10(peak*gain),rms_dbfs=20*math.log10(rms*gain)))
    if args.axe_only:
        updated={row['file']:row for row in rows}
        rows=[updated.get(row['file'],row) for row in json.loads((OUT/'manifest.json').read_text())]
    (OUT/'manifest.json').write_text(json.dumps(rows,indent=2)+'\n')
    (OUT/'LICENSE.txt').write_text((BASE/'LICENSE.txt').read_text())
    (OUT/'CREDITS.txt').write_text((BASE/'CREDITS.txt').read_text())
    (OUT/'SOURCES.md').write_text('Experimental Quake I / UT99-inspired reports and effects. Generated by tools/prepare_weapon_variants.py from the existing Freedoom BSD-3-Clause / Kenney CC0 bank (../doom-style/SOURCES.md), with original procedural resonances. Axe swings are original CC0-1.0 filtered-noise swishes with no chainsaw or other source sample. No original commercial game audio used. Source and output hashes, levels and durations are in manifest.json. Original notices are retained in LICENSE.txt and CREDITS.txt.\n')
    print(f'{len(rows)} clips, {sum(p.stat().st_size for p in OUT.glob("*.wav"))} bytes')
if __name__=='__main__':main()
