"""Deterministic experimental SFX derived from the existing licensed arena bank.
Run with Python 3 and ffmpeg. No commercial Quake/UT samples are used.
"""
from pathlib import Path
import array, hashlib, json, math, random, subprocess, wave
ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'deathmatch/audio/doom-style'
OUT=ROOT/'deathmatch/audio/experimental'
RATE=22050

def decode(path,pitch):
    raw=subprocess.check_output(['ffmpeg','-v','error','-i',str(path),'-ac','1','-ar',str(RATE),'-af',f'asetrate={int(RATE*pitch)},aresample={RATE},highpass=f=65,lowpass=f=8000','-f','f32le','-'])
    return list(array.array('f',raw))

def main():
    OUT.mkdir(exist_ok=True); rows=[]
    for rules in ['quake','ut99']:
        for label in [f'weapon_{i}{alt}' for i in range(10 if rules=='quake' else 12) for alt in ['', '_alt']]+['explosion','bounce','combo']:
            slot=int(label.split('_')[1]) if label.startswith('weapon_') else 6
            alias=([1,1,3,4,6,5,6,5,7,5] if rules=='quake' else [1,7,2,7,4,5,6,7,8,5,5,7])[slot] if label.startswith('weapon_') else 6
            source=BASE/(f'weapon_{alias}.wav' if label.startswith('weapon_') else 'explosion.wav')
            if label=="bounce":source=ROOT/"deathmatch/audio/recorded/impactMetal_light_000.ogg"
            pitch=(.83 if rules=='quake' else 1.12)*(1.14 if label.endswith('_alt') else 1)
            values=decode(source,pitch)
            duration=.13 if slot in [5,7,8] and rules=='quake' else .18 if slot in [5,7] else .46
            if not label.startswith('weapon_'):duration=.08 if label=='bounce' else .7
            n=min(len(values),int(RATE*duration));values=values[:n]
            rng=random.Random(rules+label)
            # Quake nails get a sharp metal contact; UT energy gets resonant tails.
            energy=rules=='ut99' and slot in [1,3,7,8,10,11] or rules=='quake' and slot==8
            for i in range(n):
                t=i/RATE;env=math.exp(-t*(18 if label=='bounce' else 10))
                detail=(math.sin(2*math.pi*(220+slot*61)*t+5*math.sin(2*math.pi*31*t))*.14 if energy else rng.uniform(-.10,.10)*math.exp(-t*130))
                values[i]=(values[i]+detail*env)*min(1,i/22)*min(1,(n-i)/220)
            mean=sum(values)/n;values=[v-mean for v in values]
            rms=math.sqrt(sum(v*v for v in values)/n);peak=max(map(abs,values))
            gain=min(10**(-17/20)/max(rms,1e-8),10**(-1/20)/max(peak,1e-8))
            values=[v*gain for v in values];path=OUT/f'{rules}_{label}.wav'
            with wave.open(str(path),'wb') as f:
                f.setnchannels(1);f.setsampwidth(2);f.setframerate(RATE);f.writeframes(array.array('h',(round(v*32767) for v in values)).tobytes())
            rows.append(dict(file=path.name,source=str(source.relative_to(ROOT)),source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),sha256=hashlib.sha256(path.read_bytes()).hexdigest(),seconds=n/RATE,peak_dbfs=20*math.log10(peak*gain),rms_dbfs=20*math.log10(rms*gain)))
    (OUT/'manifest.json').write_text(json.dumps(rows,indent=2)+'\n')
    (OUT/'LICENSE.txt').write_text((BASE/'LICENSE.txt').read_text())
    (OUT/'CREDITS.txt').write_text((BASE/'CREDITS.txt').read_text())
    (OUT/'SOURCES.md').write_text('Experimental Quake I / UT99-inspired reports and effects. Generated by tools/prepare_weapon_variants.py from the existing Freedoom BSD-3-Clause / Kenney CC0 bank (../doom-style/SOURCES.md), with original procedural resonances. No original commercial game audio used. Source and output hashes, levels and durations are in manifest.json. Original notices are retained in LICENSE.txt and CREDITS.txt.\n')
    print(f'{len(rows)} clips, {sum(p.stat().st_size for p in OUT.glob("*.wav"))} bytes')
if __name__=='__main__':main()
