extends "res://deathmatch/tests/special_modes.gd"
func run() -> void:
	var Config=preload("res://deathmatch/server/config.gd")
	var parsed: Dictionary=Config.parse('set sv_gametype IF\nset sv_gametypes "ig if ft"\nset ig_maplist "qsrc_dm1 qsrc_dm2"')
	check(not parsed.has("error") and parsed.values.sv_gametype=="if","Server accepts IF and normalizes its identifier")
	check(parsed.values.mode_maps["if"]==["qsrc_dm1","qsrc_dm2"] and parsed.values.mode_maps["if"]==parsed.values.mode_maps.ig,"IF shares explicit IG maplist")
	check(not Config.parse('set sv_gametypes "dm tdm ctf koth ig if ft cc tf as"').has("error"),"All ten game modes can be enabled together")
	g=load("res://deathmatch/arena.tscn").instantiate();root.add_child(g);Fixture.setup(g);await physics_frame
	g.start_host("Instafreeze",0,20,10,true,"if");g.bots.free();g.bots=null;g.set_physics_process(false);g.set_process(false)
	check(g.match_mode.kind=="if" and g.match_mode.team_game() and g.max_clients==8,"In-game host starts IF with teams and eight-player capacity")
	for rules in ["doom","quake","ut99"]:
		g.armory.select(rules);prepare("if")
		check(g.players[1].owned==[9] and g.players[1].ammo==[0,0,0,0] and not g.armory.experimental(),rules+" uses standard instagib railgun loadout")
	prepare("if")
	g.players[-1].armor=200;g.players[-1].tier=2
	g.fighters[1].position=Fixture.point(0,8);g.fighters[-1].position=Fixture.point(0,3);g.fighters[-2].position=Fixture.point(0,0);g.fighters[-3].position=Fixture.point(0,-5)
	g.players[1].yaw=0;g.players[1].pitch=0;g.players[1].cooldown=0;g._fire(1)
	check(g.match_mode.special.frozen.has(-1) and g.match_mode.special.frozen.has(-3) and not g.players[-1].dead,"Rail penetrates enemies and freezes armored targets instead of killing")
	check(not g.match_mode.special.frozen.has(-2),"Friendly teammate remains protected from rail")
	check(g.players[1].cooldown==1.5 and g.players[1].ammo==[0,0,0,0],"Standard rail cooldown and unlimited ammo retained")
	var shots: int=g.players[-1].shots;g._fire(-1);check(g.players[-1].shots==shots,"Frozen player cannot fire")
	g.match_mode.tick(.01);check(g.match_mode.scores==[1,0] and g.match_mode.special.reset_at>g.clock,"Full team freeze scores a round")
	g.match_mode.tick(.01);check(g.match_mode.scores==[1,0],"Wipe cannot score twice")
	var replica=preload("res://deathmatch/modes/match.gd").new();replica.setup(g);replica.receive(g.match_mode.snapshot())
	check(replica.kind=="if" and replica.special.frozen.size()==2 and replica.special.blocked(1),"Snapshot carries IF, frozen players and round pause")
	g.clock+=3.1;g.match_mode.tick(.01)
	check(g.match_mode.special.frozen.is_empty() and g.players[-1].owned==[9] and g.players[-1].hp==100,"Next freeze round restores railgun loadout")
	prepare("if");g.fighters[-1].position=Fixture.point();g.fighters[-3].position=Fixture.point(1,0)
	g._damage(-1,1,10000,"RAILGUN");g.match_mode.tick(2.9)
	check(g.match_mode.special.frozen.has(-1),"Thaw needs three full seconds of teammate proximity")
	g.fighters[-3].position=Fixture.point(5,0);g.match_mode.tick(.2)
	check(g.match_mode.special.frozen[-1]==0.0,"Leaving thaw radius resets progress")
	g.fighters[-3].position=Fixture.point(1,0);g.match_mode.tick(3.0)
	check(not g.match_mode.special.frozen.has(-1) and g.players[-1].hp==100 and g.players[-1].owned==[9] and g.fighters[-1].position.distance_to(Fixture.point())<.001,"Thaw restores railgun and health in place")
	g._damage(-1,1,10000,"RAILGUN");check(not g.match_mode.special.frozen.has(-1),"Thawed player receives normal spawn protection")
	prepare("if");g.fighters[-1].position=Fixture.point(9.5,0);g.fighters[-3].position=Fixture.point(10.5,0);g._damage(-1,1,10000,"RAILGUN");g.match_mode.tick(3.1)
	check(g.match_mode.special.frozen.has(-1),"Teammates cannot thaw through a wall")
	prepare("if");g.fighters[1].position=Fixture.point();g.players[1].yaw=-PI/2;g.players[1].cooldown=0;g.fighters[-1].position=Fixture.point(12,0);g._fire(1)
	check(not g.match_mode.special.frozen.has(-1),"Rail respects solid wall occlusion")
	g.players[1].melee=true;g.players[1].melee_state={};g._update_melee(1)
	check(g.players[1].melee_state.is_empty(),"Instafreeze disables physical melee like Instagib")
	var before: Array=g.players[1].owned.duplicate();g.pickups=[{"available":true,"position":g.fighters[1].position,"kind":"weapon","item":8}];g._collect(1)
	check(g.pickups[0].available and g.players[1].owned==before,"Map pickups cannot change IF loadout")
	g.pickups.clear();g.mode_maplists={"ig":["qsrc_dm2"],"ft":["qsrc_dm1"]};g.map_rotation=["qsrc_dm1"];g.votes.allowed_modes=["ig","if","ft"]
	var choices: Array=g.votes.match_choices().filter(func(row):return row.mode=="if")
	check(choices.size()==1 and choices[0].map=="qsrc_dm2","In-game vote uses IG maplist for IF")
	choices=g.lobby.choices().filter(func(row):return row.mode=="if")
	check(choices==[{"mode":"if","map":"qsrc_dm2"}],"Lobby offers the same IG maps for IF")
	g.mode_maplists.ig.append("qsrc_dm1");check(g.maps_for_mode("if")==g.maps_for_mode("ig"),"Shared maplist stays synchronized after edits")
	prepare("if");g.frag_limit=1;g._damage(-1,1,10000,"RAILGUN");g._damage(-3,1,10000,"RAILGUN");g.match_mode.tick(.01)
	check(g.intermission>0 and g.match_mode.result().begins_with("RED WINS"),"Team freeze limit ends the match")
	print("INSTAFREEZE_RESULT ",JSON.stringify(failures));g.free();quit(0 if failures.is_empty() else 1)
