extends SceneTree
const Art=preload("res://deathmatch/art.gd")
const Poses=preload("res://deathmatch/vr/poses.gd")
const Profile=preload("res://deathmatch/profile.gd")
var failures: Array=[]
func check(value: bool,label: String) -> void:
	print("PASS " if value else "FAIL ",label)
	if not value: failures.append(label)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	for handedness in [-1,1]:
		var grip:=Transform3D(Basis(Vector3.RIGHT,.8),Vector3(.3*handedness,1.2,-.3))
		var aim:=Transform3D(Basis.from_euler(Vector3(.2,-.5,.3)),grip.origin+Vector3(.04,.07,-.1))
		var pose:=Poses.held_weapon(grip,aim)
		check(pose.origin==grip.origin and pose.basis==aim.basis,"Weapon uses palm translation and independent aim rotation")
		for id in range(9):
			var weapon:=Art.weapon(id)
			root.add_child(weapon)
			weapon.transform=Art.held_transform(pose,id)
			check(weapon.to_global(Art.GRIPS[id]).distance_to(grip.origin)<.00001,"Weapon %d palm anchor aligns for hand %d"%[id,handedness])
			check(weapon.to_global(weapon.get_meta("muzzle")).is_equal_approx(Art.held_transform(pose,id)*Art.muzzle(id)),"Visual muzzle matches shot-origin calculation")
			weapon.free()
	var shotgun:=Art.weapon(3)
	var double:=Art.weapon(4)
	check(shotgun.has_node("TexturedWeapon") and double.has_node("TexturedWeapon") and double.get_node("TexturedWeapon").scale.x>1,"Super shotgun restores textured CC0 model with its original paired-bore variant")
	shotgun.free();double.free()
	var path:="/tmp/fpsloppa-profile-test.cfg"
	var config:=ConfigFile.new();config.set_value("custom","keep",42);config.save(path)
	check(Profile.save(" [VR]\nPilot ","localhost",path)==OK,"Callsign config saves")
	check(Profile.load_name(path)=="VRPilot","Callsign sanitization survives a config round trip")
	config.load(path)
	check(config.get_value("custom","keep")==42,"Saving name preserves other config settings")
	check(Profile.load_name("/tmp/fpsloppa-no-such-profile.cfg")==Profile.system_name(),"Missing config falls back to system username")
	check(Profile.clean("abcdefghijklmnopqrstuv").length()==18,"Names retain multiplayer length limit")
	var game=load("res://deathmatch/arena.tscn").instantiate();root.add_child(game)
	game.headless=false;game.spatial.setup(game)
	game.camera=game.get_node("Overview")
	game.spatial.play("weapon_7",game.camera.position,-4)
	var sound=game.spatial.active.back()
	check(absf(float(sound.get_meta("dry_db"))+17.82)<.01,"Plasma playback applies measured 13.82 dB attenuation")
	game.spatial.update_source(sound,float(sound.get_meta("dry_db")))
	check(sound.volume_db<=-17.8,"Spatial updates retain weapon normalization")
	game.free()
	print("WEAPON_SETUP_RESULT ",JSON.stringify(failures))
	quit(0 if failures.is_empty() else 1)
